CREATE TABLE `Store` 
( `Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
 `Name` NVARCHAR ( 50 ) NOT NULL,
 `Location` NVARCHAR ( 50 ) NOT NULL );

CREATE TABLE `Category` 
( `Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
 `MainCategory` NVARCHAR ( 50 ),
 `Name` NVARCHAR ( 50 ) NOT NULL );

CREATE TABLE `Invoice` ( `Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 `InvoiceNumber` TEXT UNIQUE,
 `Saved` TEXT NOT NULL DEFAULT 'Saved',
 `StoreId` INTEGER NOT NULL,
 `Date` TEXT NOT NULL,
 `InvoiceAmount` MONEY NOT NULL,
FOREIGN KEY(`StoreId`) REFERENCES `Store`(`Id`) ON DELETE SET NULL );

CREATE TABLE `ProductLink` 
( `Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 `Name` TEXT NOT NULL DEFAULT 'Unknown',
 `UoM` TEXT NOT NULL DEFAULT 'each',
 `Weighted` TEXT NOT NULL DEFAULT 'Packaged',
 `MeasurementRate` INTEGER NOT NULL DEFAULT 100,
 `CategoryId` INTEGER NOT NULL,
FOREIGN KEY(`CategoryId`) REFERENCES `Category`(`Id`) ON DELETE SET NULL );

CREATE TABLE `Product`
(`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Description` NVARCHAR ( 50 ) NOT NULL DEFAULT 'Unknown',
	`BrandName` NVARCHAR ( 50 ) NOT NULL DEFAULT 'Unknown',
	`PackSize` NCHAR ( 10 ),
	`ProductLinkId` INT NOT NULL,
FOREIGN KEY(`ProductLinkId`) REFERENCES `ProductLink`(`Id`) ON DELETE SET NULL );

CREATE TABLE `Barcode` 
( `Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 `Barcode` TEXT NOT NULL UNIQUE,
 `ProductId` INTEGER NOT NULL,
FOREIGN KEY(`ProductId`) REFERENCES `Product`(`Id`) ON DELETE SET NULL );

CREATE TABLE `InvoiceProduct` 
( `Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 `Weight` FLOAT ( 53 ),
 `Quantity` INT NOT NULL,
 `TotalPrice` MONEY,
 `ProductId` INT NOT NULL,
 `InvoiceId` INT NOT NULL,
 `Sale` TEXT NOT NULL DEFAULT 'Regular',
FOREIGN KEY(`ProductId`) REFERENCES `Product`(`Id`) ON DELETE SET NULL, 
FOREIGN KEY(`InvoiceId`) REFERENCES `Invoice`(`Id`) ON DELETE SET NULL );